// Workflow map — a concise per-agent summary of what happened in a task,
// generated by Claude Haiku from the task transcript. The user can then EDIT
// the tree and push it back into chat to re-run the task with adjusted steps.

import { query } from "@anthropic-ai/claude-agent-sdk";
import type { Message, Task, Employee } from "./types";

export interface WorkflowNode {
  label: string;
  children?: WorkflowNode[];
}

/** Summarize a task into a tree: root = task, level 1 = each agent that worked,
 *  level 2 = the concise steps that agent did. Throws on bad model output. */
export async function generateWorkflowMap(
  task: Task,
  messages: Message[],
  roster: Employee[],
): Promise<WorkflowNode> {
  const nameById = new Map(roster.map(e => [e.id, `${e.name} (${e.role})`]));
  const transcript = messages
    .map(m => {
      const who = m.fromId === null ? "User" : (nameById.get(m.fromId) ?? "Đồng nghiệp cũ");
      const content = m.content.length > 800 ? m.content.slice(0, 800) + "…" : m.content;
      return `[${who}]: ${content}`;
    })
    .join("\n\n");

  const systemPrompt =
`Bạn tóm tắt WORKFLOW của một task thành cây JSON NGẮN GỌN, để user dùng làm bản nháp chỉnh sửa rồi giao lại.

Quy tắc:
- Root: label = tên task.
- Mỗi nhánh cấp 1 = một agent CÓ THỰC SỰ làm việc trong task (label = "Tên (vai trò)"). Bỏ qua agent không tham gia.
- Nhánh cấp 2 = các BƯỚC agent đó đã làm. Mỗi bước là một HÀNH ĐỘNG, tối đa ~12 từ, tối đa 6 bước/agent.
- Chỉ mô tả HÀNH ĐỘNG đã làm (vd "Đọc file sao kê", "So sánh doanh thu theo kênh", "Xuất báo cáo PDF"). KHÔNG ghi lại nội dung kết quả/số liệu (user đã có file rồi).
- Tiếng Việt, cực ngắn gọn, không sáo rỗng.

Chỉ trả về DUY NHẤT một JSON object, KHÔNG kèm prose, KHÔNG markdown fence. Schema:
{"label":"<tên task>","children":[{"label":"<Tên (vai trò)>","children":[{"label":"<bước>"},{"label":"<bước>"}]}]}`;

  const userPrompt =
`Task: ${task.title}
Mô tả: ${task.description}

=== TRANSCRIPT ===
${transcript}`;

  let text = "";
  const gen = query({
    prompt: userPrompt,
    options: {
      systemPrompt: [systemPrompt],
      model: "claude-haiku-4-5",
      tools: [],
      settingSources: [],
      mcpServers: {},
      disallowedTools: ["mcp__pencil__*", "mcp__claude_ai_*", "mcp__figma__*"],
      maxTurns: 1,
    },
  });

  for await (const msg of gen) {
    if (msg.type === "assistant") {
      const content = msg.message.content as Array<{ type: string; text?: string }>;
      for (const block of content) {
        if (block.type === "text" && block.text) text += block.text;
      }
    }
  }

  const cleaned = text.replace(/```json\s*/gi, "").replace(/```/g, "").trim();
  const first = cleaned.indexOf("{");
  const last = cleaned.lastIndexOf("}");
  if (first < 0 || last < 0) throw new Error("Model không trả về JSON hợp lệ");

  const parsed = JSON.parse(cleaned.slice(first, last + 1)) as WorkflowNode;
  if (!parsed || typeof parsed.label !== "string") {
    throw new Error("JSON workflow thiếu trường 'label'");
  }
  return sanitize(parsed);
}

/** Defensive: ensure every node has a string label and a clean children array. */
export function sanitize(node: WorkflowNode): WorkflowNode {
  const label = typeof node.label === "string" ? node.label : String(node.label ?? "");
  const children = Array.isArray(node.children)
    ? node.children.filter(c => c && typeof c === "object").map(sanitize)
    : undefined;
  return children && children.length > 0 ? { label, children } : { label };
}
